---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: fission
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: fission
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: controller
    spec:
      containers:
      - name: controller
        image: fission/fission-bundle:minishiftalpha1
        command: ["/fission-bundle"]
        args: ["--controllerPort", "8888", "--filepath", "/filestore"]
      serviceAccountName: fission

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: router
    spec:
      containers:
      - name: router
        image: fission/fission-bundle:minishiftalpha1
        command: ["/fission-bundle"]
        args: ["--routerPort", "8888", "--controllerUrl", "http://controller", "--poolmgrUrl", "http://poolmgr"]
      serviceAccountName: fission

---
apiVersion: v1
kind: Service
metadata:
  name: poolmgr
  labels:
    svc: poolmgr
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: poolmgr

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poolmgr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: poolmgr
    spec:
      containers:
      - name: poolmgr
        image: fission/fission-bundle:minishiftalpha1
        command: ["/fission-bundle"]
        args: ["--poolmgrPort", "8888", "--controllerUrl", "http://controller"]
      serviceAccountName: fission

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubewatcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: kubewatcher
    spec:
      containers:
      - name: kubewatcher
        image: fission/fission-bundle:minishiftalpha1
        command: ["/fission-bundle"]
        args: ["--kubewatcher", "--controllerUrl", "http://controller", "--routerUrl", "http://router"]
      serviceAccountName: fission

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    svc: etcd
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    svc: etcd

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd
        env:
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://etcd:2379
        - name: ETCD_DATA_DIR
          value: /tmp/default.etcd

---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    svc: router
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: router

---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    svc: controller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: controller

---
apiVersion: v1
kind: Route
metadata:
  name: controller
  labels:
    svc: controller
spec:
  port:
    targetPort: 8888
  to:
    kind: Service
    name: controller

---
apiVersion: v1
kind: Route
metadata:
  name: router
  labels:
    svc: router
spec:
  port:
    targetPort: 8888
  to:
    kind: Service
    name: router
